### ISSUE TITLE
Is the explanation of the permission considerer?

### ISSUE THREAD

**Issue by AyoPrez** [ZeroBrain/AndroidPermissions#1]
Android recomend have a dialog to explain why the user need permissions. Is this implemented? The developer can add a text with the explanation and it will show this message in a dialog?

http://developer.android.com/intl/es/training/permissions/best-practices.html#explain

**Comment by SeongUgJung** [comment]
I wasn't implemented to request permission-dialog.
I just add no-permission's action. 

``` java
AndroidPermissions.check(this)
    .permissions(Manifest.permission.CALL_PHONE)
    .hasPermissions(new Checker.Action0() {
        @Override
        public void call(String[] permissions) {
            // do something..
        }
    })
    .noPermissions(new Checker.Action1() {
        @Override
        public void call(String[] permissions) {
            // before requesting permission, if you need to explain why.
            // do thtat.
            // showDialog 'why permissions was needed' > requestPermissions().
        }
    })
    .check();
```

I considered to add `Activity.requestPermissions()`. but I don't determine nothing.
I wanna be implemented by developers.
