### ISSUE TITLE
minSdkVersion 15

### ISSUE THREAD

**Issue by snowdream** [ZeroBrain/AndroidPermissions#2]
should minSdkVersion be lower?

**Comment by SeongUgJung** [comment]
oh. thx for your suggestion.

I'll try to do it. :)

**Comment by SeongUgJung** [comment]
I was change package .aar to .jar
so if you want, you can use lower sdk than before. (I tested 2.3.x, that's ok)

update dependencies version 1.0.0 to 1.1.0
